### ISSUE TITLE
Liquidation recovery crashed with panic

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-ecdsa#811]
Clients crashed with a panic ~~on liquidation recovery. The case that I wanted to test is a mismatch between provided `BeneficiaryAddress` and `BitcoinChainName`.~~
EDIT: The problem occurred also when I provided `BitcoinChainName = "regtest"` in the config. So previous cause of the failure is not the real one.

I provided the address generated for `regtest` network and left `BitcoinChainName` empty. In such a case, `BitcoinChainName` resolves to a default which is `mainnet`.

I propose that we implement validation for parameters provided in the config to catch possible missconfigurations.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a151d9]

goroutine 7038 [running]:
github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1.1.1(0x5083228, 0xc0008373e0, 0x0, 0x0)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:1154 +0x14b9
github.com/keep-network/keep-ecdsa/pkg/utils.DoWithRetry(0x3b9aca00, 0x1bf08eb000, 0xa06f5356a000, 0xc0002bdec8, 0x0, 0x0)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/utils/wrappers.go:29 +0x146
github.com/keep-network/keep-ecdsa/pkg/utils.DoWithDefaultRetry(...)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/utils/wrappers.go:66
github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1.1(0xc00000c378, 0xc000033700, 0x5095638, 0xc00081e180, 0x50930e8, 0xc0003f8380, 0xc00040a390, 0xc000351e60, 0xc000113170, 0x508d5d8, ...)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:991 +0x197
created by github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:990 +0x2be
```

### Configuration:

- client 1
```toml
[Extensions.TBTC.Bitcoin]
  BeneficiaryAddress = "bcrt1q2zc3j6lly2az90grnphpy2csqqj3yu7frg5x0y"
  BitcoinChainName = "regtest" 
```

- client 2
```toml
[Extensions.TBTC.Bitcoin]
  BeneficiaryAddress = "bcrt1qe24r5agrqed2y3r0ygvyq355pp5x64mhaf6un4"
  BitcoinChainName = "regtest" 
```

- client 3
```toml
[Extensions.TBTC.Bitcoin]
  BeneficiaryAddress = "bcrt1qvhtd62msyxncfqc7h9ns4rg09ghpz936vkky4x"
  BitcoinChainName = "regtest" 
```

### Logs
<details>
<summary>Full logs</summary>

```
2021-06-03T15:46:53.015+0200	WARN	keep-ecdsa	keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] terminated event received at block [46169]
2021-06-03T15:46:53.015+0200	INFO	keep-ethlike	waiting for block [46181] to confirm chain state
2021-06-03T15:47:29.012+0200	INFO	keep-tss	announcing presence
2021-06-03T15:47:29.031+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its presence
2021-06-03T15:47:29.031+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its presence
2021-06-03T15:47:29.034+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its presence
2021-06-03T15:47:29.034+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T15:47:33.554+0200	INFO	bitcoin	retrieved a vbyte fee of [%d]29.863
2021-06-03T15:47:33.555+0200	INFO	keep-tss	member [0x65849fc91f8289b401e9d8f6d306b814b7f055c3] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced supplied btc address [bcrt1q2zc3j6lly2az90grnphpy2csqqj3yu7frg5x0y] for liquidation recovery with a max fee of [29]
2021-06-03T15:47:36.818+0200	INFO	keep-tss	member [0x28bcfad75ee4c87b9089ba4c03a79b8148104da4] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced supplied btc address [bcrt1qvhtd62msyxncfqc7h9ns4rg09ghpz936vkky4x] for liquidation recovery with a max fee of [15]
2021-06-03T15:47:37.210+0200	INFO	keep-tss	member [0xb7021acafecf289fa345ecc95ecab18077530841] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced supplied btc address [bcrt1qe24r5agrqed2y3r0ygvyq355pp5x64mhaf6un4] for liquidation recovery with a max fee of [29]
2021-06-03T15:47:37.210+0200	INFO	keep-tss	successfully gathered all btc addresses
2021-06-03T15:47:37.219+0200	INFO	keep-tss	signalling readiness
2021-06-03T15:47:37.219+0200	INFO	keep-tss	member [0x65849fc91f8289b401e9d8f6d306b814b7f055c3] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its readiness
2021-06-03T15:47:37.221+0200	INFO	keep-tss	member [0xb7021acafecf289fa345ecc95ecab18077530841] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its readiness
2021-06-03T15:47:37.221+0200	INFO	keep-tss	member [0x28bcfad75ee4c87b9089ba4c03a79b8148104da4] from keep [0xbe5130b57ae3a65BB55084dBe0CD1f3d8743D776] announced its readiness
2021-06-03T15:47:37.222+0200	INFO	keep-tss	successfully signalled readiness
2021-06-03T15:47:37.223+0200	INFO	tss-lib	party {1,}: signing round 1 starting
2021-06-03T15:47:37.785+0200	INFO	tss-lib	party {1,}: signing round 2 started
2021-06-03T15:47:38.055+0200	INFO	tss-lib	party {1,}: signing round 3 started
2021-06-03T15:47:38.062+0200	INFO	tss-lib	party {1,}: signing round 4 started
2021-06-03T15:47:38.064+0200	INFO	tss-lib	party {1,}: signing round 5 started
2021-06-03T15:47:38.066+0200	INFO	tss-lib	party {1,}: signing round 6 started
2021-06-03T15:47:38.070+0200	INFO	tss-lib	party {1,}: signing round 7 started
2021-06-03T15:47:38.071+0200	INFO	tss-lib	party {1,}: signing round 8 started
2021-06-03T15:47:38.146+0200	INFO	tss-lib	party {1,}: signing round 9 started
2021-06-03T15:47:38.149+0200	INFO	tss-lib	party {1,}: signing round 10 started
2021-06-03T15:47:38.149+0200	INFO	tss-lib	party {1,}: signing finished!
2021-06-03T15:47:46.835+0200	INFO	keep-net-libp2p	number of connected peers: [2]
2021-06-03T15:48:46.835+0200	INFO	keep-net-libp2p	number of connected peers: [2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a151d9]

goroutine 7038 [running]:
github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1.1.1(0x5083228, 0xc0008373e0, 0x0, 0x0)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:1154 +0x14b9
github.com/keep-network/keep-ecdsa/pkg/utils.DoWithRetry(0x3b9aca00, 0x1bf08eb000, 0xa06f5356a000, 0xc0002bdec8, 0x0, 0x0)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/utils/wrappers.go:29 +0x146
github.com/keep-network/keep-ecdsa/pkg/utils.DoWithDefaultRetry(...)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/utils/wrappers.go:66
github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1.1(0xc00000c378, 0xc000033700, 0x5095638, 0xc00081e180, 0x50930e8, 0xc0003f8380, 0xc00040a390, 0xc000351e60, 0xc000113170, 0x508d5d8, ...)
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:991 +0x197
created by github.com/keep-network/keep-ecdsa/pkg/client.monitorKeepTerminatedEvent.func1
	/Users/jakub/workspace/keep-network/local-setup/keep-ecdsa/pkg/client/client.go:990 +0x2be
```

</details>

Tested on branch: `liquidation-recovery-integration`

**Comment by Shadowfiend** [comment]
At a glance, this is probably due to https://github.com/keep-network/keep-ecdsa/blob/liquidation-recovery-integration/pkg/client/client.go#L1154 not using `ElectrsURLWithDefault`/dereferencing the ElectrsURL in a circumstance where it may not be set. We should avoid using pointer dereferencing at all as part of the external API here (e.g. use an `IsElectrsURLConfigured` + `ElectrsURL` that returns blank if unset + `ElectrsURLWithDefault` that returns a default).

**Comment by nkuba** [comment]
Closed by https://github.com/keep-network/keep-ecdsa/pull/814
